### ISSUE TITLE
Ser mas expresivos en las definiciones de tipos

### ISSUE THREAD

**Issue by MarianoSalerno** [FedericoFuentesWeber/TPs-PdeP-2018#2]
Por ejemplo si una funcion recibe una billetera esto debe quedar reflejado en la definicion ( billetera -> billetera en lugar de float -> float) asi hablamos mas del negocio y menos de detalles de implementacion

**Comment by miguelshevchuk** [comment]
Se resolvió el caso puntual de la definición de Evento, pero se replico el error en los tipos de la segunda entrega. Por ejemplo:
Un bloque es una lista de Transacciones, pero ustedes no fueron expresivos al definir el tipo bloque.
